"""
local_ai.py - SELFIX Frontend Generation Utilities
Defines functions for generating frontend HTML using Ollama or fallback logic.
"""
/opt/SELFIX/agents/frontend_builder.py

python
Copy
Edit

import sys

PHASE = sys.argv[1] if len(sys.argv) > 1 else "practical"

if PHASE == "theory":
    print("📚 Studying design systems, UI best practices...")
    # Simulate learning: download docs, analyze UI examples, etc.
else:
    print("🛠️ Generating frontend UI...")
    # Normal generation logic

import subprocess
import os
import datetime

# Configuration
GENERATED_DIR = "/opt/SELFIX/frontend/generated"

def generate_frontend_with_ollama(prompt: str) -> str:
    """
    Uses Ollama to generate HTML/CSS from a natural language prompt.
    Falls back to dummy HTML if Ollama is unavailable.
    """
    try:
        ollama_model = "codellama"  # Change to 'mistral' or other if needed
        print(f"🔍 Generating frontend via Ollama model: {ollama_model}...")

        result = subprocess.run(
            ["ollama", "run", ollama_model],
            input=prompt,
            text=True,
            capture_output=True,
            timeout=60
        )

        if result.returncode == 0:
            print("✅ Ollama response received.")
            return result.stdout
        else:
            print(f"⚠️ Ollama returned error: {result.stderr}")
            return fallback_html(prompt)

    except Exception as e:
        print(f"❌ Error running Ollama: {e}")
        return fallback_html(prompt)


def save_generated_html(html: str) -> str:
    """
    Saves the generated HTML string to the /frontend/generated directory.
    Returns the file path.
    """
    os.makedirs(GENERATED_DIR, exist_ok=True)
    timestamp = datetime.datetime.now().strftime("%Y%m%d_%H%M%S")
    filename = f"frontend_{timestamp}.html"
    path = os.path.join(GENERATED_DIR, filename)

    with open(path, "w") as f:
        f.write(html)

    return path


def fallback_html(prompt: str) -> str:
    """
    Basic fallback HTML if Ollama is not responding.
    """
    return f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>SELFIX Frontend</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <style>
        body {{
            font-family: Arial, sans-serif;
            padding: 2rem;
            background-color: #f7f7f7;
        }}
        .container {{
            max-width: 600px;
            margin: auto;
            background: white;
            padding: 2rem;
            box-shadow: 0 0 10px rgba(0,0,0,0.1);
        }}
    </style>
</head>
<body>
    <div class="container">
        <h1>Generated by SELFIX AI</h1>
        <p><strong>Prompt:</strong> {prompt}</p>
        <p>This is fallback content. Ollama was not available.</p>
    </div>
</body>
</html>"""
